# Generated by Django 2.2.6 on 2019-11-06 05:24

from django.db import migrations, models
import users.utils.upload
import users.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191001_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=users.utils.upload.task_document_path, validators=[users.utils.validators.validate_file_size, users.utils.validators.validate_extension]),
        ),
    ]
