# Generated by Django 2.2.6 on 2019-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
