# Generated by Django 2.2.6 on 2019-10-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
